# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `CommentMailer`.
# Please instead update this file by running `bin/tapioca dsl CommentMailer`.


class CommentMailer
  class << self
    sig { params(comment: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def new_comment(comment); end
  end
end
