# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `OauthMetadataController`.
# Please instead update this file by running `bin/tapioca dsl OauthMetadataController`.


class OauthMetadataController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
